package entity

type (
	Category    string
	StateClass  string
	DeviceClass string
)

const (
	CategoryGeneral    Category = ""
	CategoryConfig     Category = "config"
	CategoryDiagnostic Category = "diagnostic"
)

const (
	StateClassMeasurement     StateClass = "measurement"
	StateClassTotal           StateClass = "total"
	StateClassTotalIncreasing StateClass = "total_increasing"
)

const (
	ButtonDeviceClassIdentify DeviceClass = "identify"
	ButtonDeviceClassRestart  DeviceClass = "restart"
	ButtonDeviceClassUpdate   DeviceClass = "update"

	BinarySensorDeviceClassBattery         DeviceClass = "battery"
	BinarySensorDeviceClassBatteryCharging DeviceClass = "battery_charging"
	BinarySensorDeviceClassCo              DeviceClass = "carbon_monoxide"
	BinarySensorDeviceClassCold            DeviceClass = "cold"
	BinarySensorDeviceClassConnectivity    DeviceClass = "connectivity"
	BinarySensorDeviceClassDoor            DeviceClass = "door"
	BinarySensorDeviceClassGarageDoor      DeviceClass = "garage_door"
	BinarySensorDeviceClassGas             DeviceClass = "gas"
	BinarySensorDeviceClassHeat            DeviceClass = "heat"
	BinarySensorDeviceClassLight           DeviceClass = "light"
	BinarySensorDeviceClassLock            DeviceClass = "lock"
	BinarySensorDeviceClassMoisture        DeviceClass = "moisture"
	BinarySensorDeviceClassMotion          DeviceClass = "motion"
	BinarySensorDeviceClassMoving          DeviceClass = "moving"
	BinarySensorDeviceClassOccupancy       DeviceClass = "occupancy"
	BinarySensorDeviceClassOpening         DeviceClass = "opening"
	BinarySensorDeviceClassPlug            DeviceClass = "plug"
	BinarySensorDeviceClassPower           DeviceClass = "power"
	BinarySensorDeviceClassPresence        DeviceClass = "presence"
	BinarySensorDeviceClassProblem         DeviceClass = "problem"
	BinarySensorDeviceClassRunning         DeviceClass = "running"
	BinarySensorDeviceClassSafety          DeviceClass = "safety"
	BinarySensorDeviceClassSmoke           DeviceClass = "smoke"
	BinarySensorDeviceClassSound           DeviceClass = "sound"
	BinarySensorDeviceClassTamper          DeviceClass = "tamper"
	BinarySensorDeviceClassUpdate          DeviceClass = "update"
	BinarySensorDeviceClassVibration       DeviceClass = "vibration"
	BinarySensorDeviceClassWindow          DeviceClass = "window"

	SensorDeviceClassDate                          DeviceClass = "date"
	SensorDeviceClassEnum                          DeviceClass = "enum"
	SensorDeviceClassTimestamp                     DeviceClass = "timestamp"
	SensorDeviceClassApparentPower                 DeviceClass = "apparent_power"
	SensorDeviceClassAqi                           DeviceClass = "aqi"
	SensorDeviceClassArea                          DeviceClass = "area"
	SensorDeviceClassAtmosphericPressure           DeviceClass = "atmospheric_pressure"
	SensorDeviceClassBattery                       DeviceClass = "battery"
	SensorDeviceClassBloodGlucoseConcentration     DeviceClass = "blood_glucose_concentration"
	SensorDeviceClassCo                            DeviceClass = "carbon_monoxide"
	SensorDeviceClassCo2                           DeviceClass = "carbon_dioxide"
	SensorDeviceClassConductivity                  DeviceClass = "conductivity"
	SensorDeviceClassCurrent                       DeviceClass = "current"
	SensorDeviceClassDataRate                      DeviceClass = "data_rate"
	SensorDeviceClassDataSize                      DeviceClass = "data_size"
	SensorDeviceClassDistance                      DeviceClass = "distance"
	SensorDeviceClassDuration                      DeviceClass = "duration"
	SensorDeviceClassEnergy                        DeviceClass = "energy"
	SensorDeviceClassEnergyStorage                 DeviceClass = "energy_storage"
	SensorDeviceClassFrequency                     DeviceClass = "frequency"
	SensorDeviceClassGas                           DeviceClass = "gas"
	SensorDeviceClassHumidity                      DeviceClass = "humidity"
	SensorDeviceClassIlluminance                   DeviceClass = "illuminance"
	SensorDeviceClassIrradiance                    DeviceClass = "irradiance"
	SensorDeviceClassMoisture                      DeviceClass = "moisture"
	SensorDeviceClassMonetary                      DeviceClass = "monetary"
	SensorDeviceClassNitrogenDioxide               DeviceClass = "nitrogen_dioxide"
	SensorDeviceClassNitrogenMonoxide              DeviceClass = "nitrogen_monoxide"
	SensorDeviceClassNitrousOxide                  DeviceClass = "nitrous_oxide"
	SensorDeviceClassOzone                         DeviceClass = "ozone"
	SensorDeviceClassPh                            DeviceClass = "ph"
	SensorDeviceClassPm1                           DeviceClass = "pm1"
	SensorDeviceClassPm10                          DeviceClass = "pm10"
	SensorDeviceClassPm25                          DeviceClass = "pm25"
	SensorDeviceClassPowerFactor                   DeviceClass = "power_factor"
	SensorDeviceClassPower                         DeviceClass = "power"
	SensorDeviceClassPrecipitation                 DeviceClass = "precipitation"
	SensorDeviceClassPrecipitationIntensity        DeviceClass = "precipitation_intensity"
	SensorDeviceClassPressure                      DeviceClass = "pressure"
	SensorDeviceClassReactivePower                 DeviceClass = "reactive_power"
	SensorDeviceClassSignalStrength                DeviceClass = "signal_strength"
	SensorDeviceClassSoundPressure                 DeviceClass = "sound_pressure"
	SensorDeviceClassSpeed                         DeviceClass = "speed"
	SensorDeviceClassSulphurDioxide                DeviceClass = "sulphur_dioxide"
	SensorDeviceClassTemperature                   DeviceClass = "temperature"
	SensorDeviceClassVolatileOrganicCompounds      DeviceClass = "volatile_organic_compounds"
	SensorDeviceClassVolatileOrganicCompoundsParts DeviceClass = "volatile_organic_compounds_parts"
	SensorDeviceClassVoltage                       DeviceClass = "voltage"
	SensorDeviceClassVolume                        DeviceClass = "volume"
	SensorDeviceClassVolumeStorage                 DeviceClass = "volume_storage"
	SensorDeviceClassVolumeFlowRate                DeviceClass = "volume_flow_rate"
	SensorDeviceClassWater                         DeviceClass = "water"
	SensorDeviceClassWeight                        DeviceClass = "weight"
	SensorDeviceClassWindSpeed                     DeviceClass = "wind_speed"

	CoverDeviceClassAwning  DeviceClass = "awning"
	CoverDeviceClassBlind   DeviceClass = "blind"
	CoverDeviceClassCurtain DeviceClass = "curtain"
	CoverDeviceClassDamper  DeviceClass = "damper"
	CoverDeviceClassDoor    DeviceClass = "door"
	CoverDeviceClassGarage  DeviceClass = "garage"
	CoverDeviceClassGate    DeviceClass = "gate"
	CoverDeviceClassShade   DeviceClass = "shade"
	CoverDeviceClassShutter DeviceClass = "shutter"
	CoverDeviceClassWindow  DeviceClass = "window"

	NumberDeviceClassApparentPower                 DeviceClass = "apparent_power"
	NumberDeviceClassAqi                           DeviceClass = "aqi"
	NumberDeviceClassArea                          DeviceClass = "area"
	NumberDeviceClassAtmosphericPressure           DeviceClass = "atmospheric_pressure"
	NumberDeviceClassBattery                       DeviceClass = "battery"
	NumberDeviceClassBloodGlucoseConcentration     DeviceClass = "blood_glucose_concentration"
	NumberDeviceClassCarbonMonoxide                DeviceClass = "carbon_monoxide"
	NumberDeviceClassCarbonDioxide                 DeviceClass = "carbon_dioxide"
	NumberDeviceClassConductivity                  DeviceClass = "conductivity"
	NumberDeviceClassCurrent                       DeviceClass = "current"
	NumberDeviceClassDataRate                      DeviceClass = "data_rate"
	NumberDeviceClassDataSize                      DeviceClass = "data_size"
	NumberDeviceClassDistance                      DeviceClass = "distance"
	NumberDeviceClassDuration                      DeviceClass = "duration"
	NumberDeviceClassEnergy                        DeviceClass = "energy"
	NumberDeviceClassEnergyDistance                DeviceClass = "energy_distance"
	NumberDeviceClassEnergyStorage                 DeviceClass = "energy_storage"
	NumberDeviceClassFrequency                     DeviceClass = "frequency"
	NumberDeviceClassGas                           DeviceClass = "gas"
	NumberDeviceClassHumidity                      DeviceClass = "humidity"
	NumberDeviceClassIlluminance                   DeviceClass = "illuminance"
	NumberDeviceClassIrradiance                    DeviceClass = "irradiance"
	NumberDeviceClassMoisture                      DeviceClass = "moisture"
	NumberDeviceClassMonetary                      DeviceClass = "monetary"
	NumberDeviceClassNitrogenDioxide               DeviceClass = "nitrogen_dioxide"
	NumberDeviceClassNitrogenMonoxide              DeviceClass = "nitrogen_monoxide"
	NumberDeviceClassNitrousOxide                  DeviceClass = "nitrous_oxide"
	NumberDeviceClassOzone                         DeviceClass = "ozone"
	NumberDeviceClassPh                            DeviceClass = "ph"
	NumberDeviceClassPm1                           DeviceClass = "pm1"
	NumberDeviceClassPm10                          DeviceClass = "pm10"
	NumberDeviceClassPm25                          DeviceClass = "pm25"
	NumberDeviceClassPowerFactor                   DeviceClass = "power_factor"
	NumberDeviceClassPower                         DeviceClass = "power"
	NumberDeviceClassPrecipitation                 DeviceClass = "precipitation"
	NumberDeviceClassPrecipitationIntensity        DeviceClass = "precipitation_intensity"
	NumberDeviceClassPressure                      DeviceClass = "pressure"
	NumberDeviceClassReactivePower                 DeviceClass = "reactive_power"
	NumberDeviceClassSignalStrength                DeviceClass = "signal_strength"
	NumberDeviceClassSoundPressure                 DeviceClass = "sound_pressure"
	NumberDeviceClassSpeed                         DeviceClass = "speed"
	NumberDeviceClassSulphurDioxide                DeviceClass = "sulphur_dioxide"
	NumberDeviceClassTemperature                   DeviceClass = "temperature"
	NumberDeviceClassVolatileOrganicCompounds      DeviceClass = "volatile_organic_compounds"
	NumberDeviceClassVolatileOrganicCompoundsParts DeviceClass = "volatile_organic_compounds_parts"
	NumberDeviceClassVoltage                       DeviceClass = "voltage"
	NumberDeviceClassVolume                        DeviceClass = "volume"
	NumberDeviceClassVolumeStorage                 DeviceClass = "volume_storage"
	NumberDeviceClassVolumeFlowRate                DeviceClass = "volume_flow_rate"
	NumberDeviceClassWater                         DeviceClass = "water"
	NumberDeviceClassWeight                        DeviceClass = "weight"
	NumberDeviceClassWindDirection                 DeviceClass = "wind_direction"
	NumberDeviceClassWindSpeed                     DeviceClass = "wind_speed"

	SwitchDeviceClassOutlet DeviceClass = "outlet"
	SwitchDeviceClassSwitch DeviceClass = "switch"

	UpdateDeviceClass DeviceClass = "firmware"

	ValveDeviceClassWater DeviceClass = "water"
	ValveDeviceClassGas   DeviceClass = "gas"
)
